beneficiaries_data = [
    {"beneficiary_id": "ben001", "name": "Maria Santos",      "dietary_needs": ["low-sodium"]},
    {"beneficiary_id": "ben002", "name": "Juan dela Cruz",    "dietary_needs": ["diabetic"]},
    {"beneficiary_id": "ben003", "name": "Ana Reyes",         "dietary_needs": []},
    {"beneficiary_id": "ben004", "name": "Mark Villanueva",   "dietary_needs": ["vegetarian"]},
    {"beneficiary_id": "ben005", "name": "Grace Lim",         "dietary_needs": ["lacto-vegetarian"]},
    {"beneficiary_id": "ben006", "name": "Peter Gonzales",    "dietary_needs": ["low-sugar"]},
    {"beneficiary_id": "ben007", "name": "Liza Pascual",      "dietary_needs": ["gluten-free"]},
    {"beneficiary_id": "ben008", "name": "Enrique Ramos",     "dietary_needs": ["no-pork"]},
    {"beneficiary_id": "ben009", "name": "Cecilia Uy",        "dietary_needs": ["pregnant"]},
    {"beneficiary_id": "ben010", "name": "Ramon Bautista",    "dietary_needs": ["diabetic", "low-sodium"]},
    {"beneficiary_id": "ben011", "name": "Nina Alcantara",    "dietary_needs": []},
    {"beneficiary_id": "ben012", "name": "Ernesto Cruz",      "dietary_needs": ["high-protein"]},
    {"beneficiary_id": "ben013", "name": "Julia Tan",         "dietary_needs": ["vegetarian", "low-sodium"]},
    {"beneficiary_id": "ben014", "name": "Carlos Medina",     "dietary_needs": []},
    {"beneficiary_id": "ben015", "name": "Elena Garcia",      "dietary_needs": ["lactose-intolerant"]},
    {"beneficiary_id": "ben016", "name": "Miguel Lopez",      "dietary_needs": ["low-carb"]},
    {"beneficiary_id": "ben017", "name": "Rosa Santos",       "dietary_needs": ["no-seafood"]},
    {"beneficiary_id": "ben018", "name": "Josefa Reyes",      "dietary_needs": ["vegetarian"]},
    {"beneficiary_id": "ben019", "name": "Andres Villanueva", "dietary_needs": ["diabetic"]},
    {"beneficiary_id": "ben020", "name": "Patricia Lim",      "dietary_needs": ["low-sodium", "low-carb"]},
]
